
import React from "react";
import secondsToTime from "../utils/secondsToTime";
import { AlbumByIdResponseData } from "./generated/models";

// No need to define your own types/interfaces for passed props. Just import the autogenerated one. Nifty!
type Props = {
  data: AlbumByIdResponseData;
};

const DataTable: React.FunctionComponent<Props> = ({ data }) => (
  <div className="flex flex-col items-center text-white">
    <p className="text-3xl font-bold my-4">&quot;{data?.Album?.Title}&quot;</p>
    <p className="text-lg font-bold mb-4"> {data?.Album?.Artist?.Name} </p>
    <table className="table-auto w-full">
      <thead>
        <tr>
          <th className="border-2 px-4 py-2">Name</th>
          <th className="border-2 px-4 py-2">Composer</th>
          <th className="border-2 px-4 py-2">Length</th>
        </tr>
      </thead>
      <tbody>
        {data?.Album?.Track.map((track) => (
          <tr key={track.TrackId}>
            <td className="border-2  px-4 py-2">{track.Name}</td>
            <td className="border-2  px-4 py-2">{track.Composer}</td>
            <td className="border-2 px-4 py-2">
              {secondsToTime(track.Milliseconds / 1000)}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

export default DataTable;
